// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:contact_app/data/source/hive/adapters/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ContactHiveAdapter());
    registerAdapter(UserHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ContactHiveAdapter());
    registerAdapter(UserHiveAdapter());
  }
}
