// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaer2Cf24FsoHG5VatV7OXR6ZJ6kTuIls',
    appId: '1:751563028957:web:a40f849bcc8ae4fb491e34',
    messagingSenderId: '751563028957',
    projectId: 'contact-app-f465a',
    authDomain: 'contact-app-f465a.firebaseapp.com',
    storageBucket: 'contact-app-f465a.firebasestorage.app',
    measurementId: 'G-KVMYTGSVR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApuE6whfe8afJoPPW1ubK1wat8ePQkMtM',
    appId: '1:751563028957:android:a118c302665a0d71491e34',
    messagingSenderId: '751563028957',
    projectId: 'contact-app-f465a',
    storageBucket: 'contact-app-f465a.firebasestorage.app',
  );
}
